project_name: tiletool
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_arm64
      - darwin_amd64
      - windows_amd64
universal_binaries:
  - replace: true
archives:
  - format: zip
    replacements:
      darwin: macOS
      windows: Windows
      amd64: 64-bit
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
